GET http://localhost:3001/api/notes
###
DELETE http://localhost:3001/api/notes/3
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code Rest Client",
    "important": false
}